Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrderedMSP
    MSPDir: crypto-config/ordererOrganizations/loc.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

Profile:
Defaults: Capabilities, channel and application
